spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: root


  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    # Hibernate ddl auto (create, create-drop, validate, update)
    hibernate:
      ddl-auto:  update